/// Flutter icons BottomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomIcons
///      fonts:
///       - asset: fonts/BottomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomIcons {
  BottomIcons._();

  static const _kFontFam = 'BottomIcons';
  static const String? _kFontPkg = null;

  static const IconData fi_rr_pulse = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_rr_crown = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_rr_interlining = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_rr_star = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_rr_stats = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_sr_star = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
